/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TalkAboutYourPetRouteImport } from './routes/talk-about-your-pet'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CarePetIdRouteImport } from './routes/care.$petId'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as PetsNewRouteImport } from './routes/pets.new'
import { Route as ToolsFeedingCalculatorRouteImport } from './routes/tools.feeding-calculator'
import { Route as CarePetIdQrRouteImport } from './routes/care.$petId.qr'
import { Route as PetsPetIdEditRouteImport } from './routes/pets.$petId.edit'
import { Route as PetsPetIdMedicationsRouteImport } from './routes/pets.$petId.medications'
import { Route as ApiPublicHooksWeeklyGuideRouteImport } from './routes/api/public/hooks/weekly-guide'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkAboutYourPetRoute = TalkAboutYourPetRouteImport.update({
  id: '/talk-about-your-pet',
  path: '/talk-about-your-pet',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePetIdRoute = CarePetIdRouteImport.update({
  id: '/care/$petId',
  path: '/care/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFeedingCalculatorRoute = ToolsFeedingCalculatorRouteImport.update({
  id: '/tools/feeding-calculator',
  path: '/tools/feeding-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePetIdQrRoute = CarePetIdQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => CarePetIdRoute,
} as any)
const PetsPetIdEditRoute = PetsPetIdEditRouteImport.update({
  id: '/pets/$petId/edit',
  path: '/pets/$petId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdMedicationsRoute = PetsPetIdMedicationsRouteImport.update({
  id: '/pets/$petId/medications',
  path: '/pets/$petId/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyGuideRoute =
  ApiPublicHooksWeeklyGuideRouteImport.update({
    id: '/api/public/hooks/weekly-guide',
    path: '/api/public/hooks/weekly-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talk-about-your-pet': typeof TalkAboutYourPetRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/care/$petId': typeof CarePetIdRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRoute
  '/pets/new': typeof PetsNewRoute
  '/tools/feeding-calculator': typeof ToolsFeedingCalculatorRoute
  '/guides/': typeof GuidesIndexRoute
  '/care/$petId/qr': typeof CarePetIdQrRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/pets/$petId/medications': typeof PetsPetIdMedicationsRoute
  '/api/public/hooks/weekly-guide': typeof ApiPublicHooksWeeklyGuideRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talk-about-your-pet': typeof TalkAboutYourPetRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/care/$petId': typeof CarePetIdRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRoute
  '/pets/new': typeof PetsNewRoute
  '/tools/feeding-calculator': typeof ToolsFeedingCalculatorRoute
  '/guides': typeof GuidesIndexRoute
  '/care/$petId/qr': typeof CarePetIdQrRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/pets/$petId/medications': typeof PetsPetIdMedicationsRoute
  '/api/public/hooks/weekly-guide': typeof ApiPublicHooksWeeklyGuideRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talk-about-your-pet': typeof TalkAboutYourPetRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/care/$petId': typeof CarePetIdRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRoute
  '/pets/new': typeof PetsNewRoute
  '/tools/feeding-calculator': typeof ToolsFeedingCalculatorRoute
  '/guides/': typeof GuidesIndexRoute
  '/care/$petId/qr': typeof CarePetIdQrRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/pets/$petId/medications': typeof PetsPetIdMedicationsRoute
  '/api/public/hooks/weekly-guide': typeof ApiPublicHooksWeeklyGuideRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/llms.txt'
    | '/onboarding'
    | '/premium'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reminders'
    | '/settings'
    | '/sitemap.xml'
    | '/talk-about-your-pet'
    | '/templates'
    | '/terms'
    | '/care/$petId'
    | '/guides/$slug'
    | '/pets/new'
    | '/tools/feeding-calculator'
    | '/guides/'
    | '/care/$petId/qr'
    | '/pets/$petId/edit'
    | '/pets/$petId/medications'
    | '/api/public/hooks/weekly-guide'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/llms.txt'
    | '/onboarding'
    | '/premium'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reminders'
    | '/settings'
    | '/sitemap.xml'
    | '/talk-about-your-pet'
    | '/templates'
    | '/terms'
    | '/care/$petId'
    | '/guides/$slug'
    | '/pets/new'
    | '/tools/feeding-calculator'
    | '/guides'
    | '/care/$petId/qr'
    | '/pets/$petId/edit'
    | '/pets/$petId/medications'
    | '/api/public/hooks/weekly-guide'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/llms.txt'
    | '/onboarding'
    | '/premium'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reminders'
    | '/settings'
    | '/sitemap.xml'
    | '/talk-about-your-pet'
    | '/templates'
    | '/terms'
    | '/care/$petId'
    | '/guides/$slug'
    | '/pets/new'
    | '/tools/feeding-calculator'
    | '/guides/'
    | '/care/$petId/qr'
    | '/pets/$petId/edit'
    | '/pets/$petId/medications'
    | '/api/public/hooks/weekly-guide'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  RemindersRoute: typeof RemindersRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TalkAboutYourPetRoute: typeof TalkAboutYourPetRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  CarePetIdRoute: typeof CarePetIdRouteWithChildren
  GuidesSlugRoute: typeof GuidesSlugRoute
  PetsNewRoute: typeof PetsNewRoute
  ToolsFeedingCalculatorRoute: typeof ToolsFeedingCalculatorRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  PetsPetIdEditRoute: typeof PetsPetIdEditRoute
  PetsPetIdMedicationsRoute: typeof PetsPetIdMedicationsRoute
  ApiPublicHooksWeeklyGuideRoute: typeof ApiPublicHooksWeeklyGuideRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk-about-your-pet': {
      id: '/talk-about-your-pet'
      path: '/talk-about-your-pet'
      fullPath: '/talk-about-your-pet'
      preLoaderRoute: typeof TalkAboutYourPetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care/$petId': {
      id: '/care/$petId'
      path: '/care/$petId'
      fullPath: '/care/$petId'
      preLoaderRoute: typeof CarePetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/feeding-calculator': {
      id: '/tools/feeding-calculator'
      path: '/tools/feeding-calculator'
      fullPath: '/tools/feeding-calculator'
      preLoaderRoute: typeof ToolsFeedingCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care/$petId/qr': {
      id: '/care/$petId/qr'
      path: '/qr'
      fullPath: '/care/$petId/qr'
      preLoaderRoute: typeof CarePetIdQrRouteImport
      parentRoute: typeof CarePetIdRoute
    }
    '/pets/$petId/edit': {
      id: '/pets/$petId/edit'
      path: '/pets/$petId/edit'
      fullPath: '/pets/$petId/edit'
      preLoaderRoute: typeof PetsPetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId/medications': {
      id: '/pets/$petId/medications'
      path: '/pets/$petId/medications'
      fullPath: '/pets/$petId/medications'
      preLoaderRoute: typeof PetsPetIdMedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-guide': {
      id: '/api/public/hooks/weekly-guide'
      path: '/api/public/hooks/weekly-guide'
      fullPath: '/api/public/hooks/weekly-guide'
      preLoaderRoute: typeof ApiPublicHooksWeeklyGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CarePetIdRouteChildren {
  CarePetIdQrRoute: typeof CarePetIdQrRoute
}

const CarePetIdRouteChildren: CarePetIdRouteChildren = {
  CarePetIdQrRoute: CarePetIdQrRoute,
}

const CarePetIdRouteWithChildren = CarePetIdRoute._addFileChildren(
  CarePetIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  RemindersRoute: RemindersRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TalkAboutYourPetRoute: TalkAboutYourPetRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  CarePetIdRoute: CarePetIdRouteWithChildren,
  GuidesSlugRoute: GuidesSlugRoute,
  PetsNewRoute: PetsNewRoute,
  ToolsFeedingCalculatorRoute: ToolsFeedingCalculatorRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  PetsPetIdEditRoute: PetsPetIdEditRoute,
  PetsPetIdMedicationsRoute: PetsPetIdMedicationsRoute,
  ApiPublicHooksWeeklyGuideRoute: ApiPublicHooksWeeklyGuideRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
